### ISSUE TITLE
BQExtensionVSCode: Update Cache doesn't show up in vscode

### ISSUE THREAD

**Issue by amirali-shfz** [kitta65/bq-extension-vscode#233]
<img width="928" alt="Screenshot 2023-09-21 at 11 26 15 AM" src="https://github.com/kitta65/bq-extension-vscode/assets/25187424/74c3aa60-f172-4d2b-8b97-1fd5bfc014ff">

**Comment by kitta65** [comment]
Maybe BQExtensionVSCode is not activated.
Try renaming your file to `xxx.bigquery` or `xxx.bq`.
If you like other file extension (e.g. `xxx.bqsql`), see [advanced settins](https://github.com/kitta65/bq-extension-vscode#advanced-settings) in README.md.
