### ISSUE TITLE
Cannot parse stdout

### ISSUE THREAD

**Issue by GaryLiuTelus** [kitta65/bq-extension-vscode#529]
I installed sqllite3 and the extension, and every time I update the cache, I got the below error: 
![image](https://github.com/user-attachments/assets/7c35a113-17a2-4b16-a742-e0c4680683b3)
And the column/table name autocompletion does not work. What could be the issues? 

I did not see any error message in the output pane though.

**Comment by kitta65** [comment]
I made a slight change in latest version (v0.0.54). https://github.com/kitta65/bq-extension-vscode/commit/31c054c724d65193fd91f4d52ce846c8fe2ea1ec

Can you tell me if your problem still exists?

**Comment by GaryLiuTelus** [comment]
Thank you for the response. But it's weird that the `update cache` command disappears after I installed the new version. Not sure if anything wrong from side though.
